### ISSUE TITLE
commit error when the file is deleted

### ISSUE THREAD

**Issue by michelfei** [my2iu/PlomGit#2]
If the file is deleted, I can't stage the change and a error shows

![image](https://user-images.githubusercontent.com/16935668/146874421-ffeb6015-9d9f-4c29-9e02-ea804eb5c176.png)

**Comment by my2iu** [comment]
I’m on vacation, so I don’t have access to my flutter development box right now, but I’ll try to take a look when I have the chance (but it might take a few weeks)

**Comment by my2iu** [comment]
I was able to get something running. It turns out I’m using libgit’s index_add to stage things and index_remove to unstage things, but I think libgit expects people to use index_remove to stage removed files and index_add to unstage such files. I’ll investigate further. Apple’s App Store reviews are probably pretty slow over the holidays, so even if I get this fixed soon, it will still likely be a week or two before a fix can be released to the App Store.

**Comment by michelfei** [comment]
That's all right. I’m not in a rush.Take your time.

**Comment by my2iu** [comment]
Ok, I've submitted a fixed version to the iOS App Store. If everything is fine, then it will take a few days or possibly a couple of weeks for it to work through the review process and be released. I do not have a copy of my Android signing key accessible to me at the moment, so updated Android versions may take a couple of weeks before it will be available.

**Comment by my2iu** [comment]
I forgot to make the Android release with these fixes earlier. I'm deploying a release now though, so I'm closing the issue.
