### ISSUE TITLE
Will you consider adding the function of custom folder?

### ISSUE THREAD

**Issue by wyue1227** [my2iu/PlomGit#4]
I hope to use it with obsidian on iOS.

**Comment by my2iu** [comment]
I looked into that previously, but libgit2 uses standard C file APIs for working with git files while iOS and Android use custom APIs for working with custom folders outside an app’s control. So libgit2 would need to be rewritten to use different APIs for accessing files, which is outside the scope of this project. 

It would probably be easier for Obsidian to add support for using outside folders to store its data (or for Apple and Google to redesign their file security scheme to map their files into the OS file system properly instead of the hacky, non-performant thing they implemented instead).

**Comment by wyue1227** [comment]
Ok thanks😁
